apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hostname }}`)
      {{ with .Values.service }}
      services:
        - name: {{ .name }}
          port: {{ .port }} 
      {{- end }}
  tls:
    secretName: {{ .Release.Name }}-cert
